# Generated by Django 4.2.11 on 2024-04-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=64)),
                ('car_year', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=1024)),
                ('fuel', models.CharField(choices=[('GASOLINE', 'GASOLINE'), ('ALCOHOL', 'ALCOHOL'), ('DIESEL', 'DIESEL')], max_length=10)),
                ('kilometers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motor_detail', models.TextField(max_length=256)),
                ('car_type', models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC'), ('MANUAL', 'MANUAL')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('version', models.CharField(max_length=24)),
                ('photo_car', models.ImageField(upload_to='')),
            ],
        ),
    ]
