# Generated by Django 4.2.11 on 2024-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='situation',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
